// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbd65N_Aqp5cQTUkWFIPJjSV3EQLA3z0E',
    appId: '1:303489378411:web:e09d4afb80006b9b60292e',
    messagingSenderId: '303489378411',
    projectId: 'careconnect-c275c',
    authDomain: 'careconnect-c275c.firebaseapp.com',
    storageBucket: 'careconnect-c275c.firebasestorage.app',
    measurementId: 'G-TCXNQP4257',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbIDjL12ePALgsoH12ebLk82_-02t2J7U',
    appId: '1:303489378411:android:2e8ba7bd58a0754c60292e',
    messagingSenderId: '303489378411',
    projectId: 'careconnect-c275c',
    storageBucket: 'careconnect-c275c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2rgeuJf8L3_M98oKXbBN98RCreHviU-s',
    appId: '1:303489378411:ios:2ae939dd560cbaf860292e',
    messagingSenderId: '303489378411',
    projectId: 'careconnect-c275c',
    storageBucket: 'careconnect-c275c.firebasestorage.app',
    iosBundleId: 'com.example.flutter1pratice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2rgeuJf8L3_M98oKXbBN98RCreHviU-s',
    appId: '1:303489378411:ios:2ae939dd560cbaf860292e',
    messagingSenderId: '303489378411',
    projectId: 'careconnect-c275c',
    storageBucket: 'careconnect-c275c.firebasestorage.app',
    iosBundleId: 'com.example.flutter1pratice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbd65N_Aqp5cQTUkWFIPJjSV3EQLA3z0E',
    appId: '1:303489378411:web:b693c8bf3f51f04e60292e',
    messagingSenderId: '303489378411',
    projectId: 'careconnect-c275c',
    authDomain: 'careconnect-c275c.firebaseapp.com',
    storageBucket: 'careconnect-c275c.firebasestorage.app',
    measurementId: 'G-WFKEWSM4FZ',
  );
}
